name: Cypress Chrome Tests

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 6 * * *'

jobs:
  initialize_cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Container Initialization
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.docker
          key: ${{ runner.os }}-container-initialization

  chrome:
    needs: initialize_cache
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    container: cypress/browsers:node14.17.0-chrome88-ff89

    steps:
      - name: Restore Cached Initialization
        uses: actions/cache@v2
        with:
          path: ~/.docker
          key: ${{ runner.os }}-container-initialization
          restore-keys: ${{ runner.os }}-container-initialization

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules-

      - name: Cypress Run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headless: true
          parallel: ${{ matrix.containers }}
          record: true
          group: 'UI - Chrome'
          cache: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
