name: Cypress Chrome Tests

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 6 * * *'

jobs:
  initialize_cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Container Initialization
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.docker
          key: ${{ runner.os }}-container-initialization

  chrome:
    needs: initialize_cache
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    container: cypress/browsers:node18.12.0-chrome107

    steps:
      - name: Restore Cached Initialization
        uses: actions/cache@v2
        with:
          path: ~/.docker
          key: ${{ runner.os }}-container-initialization
          restore-keys: ${{ runner.os }}-container-initialization

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Dependencies and Cypress Binary
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      # Added step to change permissions of Cypress cache directory
      - name: Change permissions of Cypress cache directory
        run: chmod -R 777 /github/home/.cache/Cypress

      - name: Cypress Run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headless: true
          parallel: true
          record: true
          group: 'UI - Chrome'
          cache: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
