name: Cypress chrome tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  chrome:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: cypress/browsers:node14.17.0-chrome88-ff89
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1,2,3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: run tests on chrome
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          browser: chrome
          headless: true
          group: 'UI - Chrome'

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}


